#!/bin/bash

# Error handler
set -e

# 
apt-get install --yes --no-install-recommends tree

# For ipywidgets
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension